### ISSUE TITLE
Text on top of custom map icons

### ISSUE THREAD

**Issue by DlljsCodes** [TechnicJelle/BlueMapWebAddons#1]
As you can see, the name of the map displays on top of the custom map icon, and is not properly positioned to the left of the icon.
![image](https://github.com/TechnicJelle/BlueMapWebScripts/assets/64469452/968fdf45-3088-46a2-b414-e707e5e13116)
Am I just gonna have to add a few spaces to the map's display name?

**Comment by TechnicJelle** [comment]
This should be fixed by the CSS style file that's also included.
Are you 100% sure you've got that set up correctly?

I'll double-check it on my end as well.
Perhaps something has changed in the BlueMap Webapp code since this guide was written?
Could you tell me which BlueMap version that webapp is?

**Comment by DlljsCodes** [comment]
Running BlueMap 3.20.

**Comment by TechnicJelle** [comment]
I just tested it out, and it still works fine for me:
![image](https://github.com/TechnicJelle/BlueMapWebScripts/assets/22576047/179c4b31-c390-4675-a4cd-8e7355ecccd5)

To test, I also un-registered the CSS style file, to see what that looked like. And indeed, that caused the text to overlap over the icon:
![image](https://github.com/TechnicJelle/BlueMapWebScripts/assets/22576047/a5f1679f-f140-42a2-b6db-c861f20fa864)

So please make sure you really have the CSS file applied and registered, as well as the JS script file.
Here's a guide on how to do that: https://bluemap.bluecolored.de/community/Customisation.html#theme-and-look

If the instructions in the guide are too unclear about this, please tell me, so I can try and make it clearer!
I wrote most of this while being ill, so there are definitely things I could word better.

**Comment by DlljsCodes** [comment]
Yep, I spelt the name of the file wrong in the config file! 😜

Thanks for the help.

**Comment by DlljsCodes** [comment]
Yep, I spelt the name of the file wrong in the config file! 😜

Thanks for the help.
