### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Kirin92** [TechnicJelle/BlueMapWebAddons#5]
I'm sorry I am not a coding expert but somehow the .js is not working for me. I tested it first with a test.js that says hello world in the console and it works. Then I changed it to the BlueMapCopyCoordinates.js, reloaded BlueMap and I get an error in the console.
![chrome_8h13U0r9O8](https://github.com/user-attachments/assets/ca76157b-16a0-40a8-a2f8-fca4881bc0b8)
![chrome_CdQbgTzqM6](https://github.com/user-attachments/assets/5746a4da-3cb6-49c1-a5c4-4196efa2772e)

**Comment by TechnicJelle** [comment]
You seem to somehow have downloaded the wrong file.
What you show here is actually HTML code, not JS code.

To fix this, go here: https://github.com/TechnicJelle/BlueMapWebAddons/blob/main/copy-coordinates/BlueMapCopyCoordinates.js and click this button:
![image](https://github.com/user-attachments/assets/679f82ee-92c8-4b96-9db6-53cf78115031)

Then open your `BlueMapCopyCoordinates.js` file on your computer/server with a text editor, and replace the contents with what you copied.
That should fix it.

**Comment by Kirin92** [comment]
Oh! Alright thank you!

**Comment by Kirin92** [comment]
I did it now and reloaded Bluemaps and even restarted the server. Unfortunately it's the same error, even with the correct .js
![chrome_vOaL7KAY7T](https://github.com/user-attachments/assets/507ceda3-cae7-42b0-aad3-73114fb61ad5)

**Comment by TechnicJelle** [comment]
To refresh completely, try this:
`F12` -> `Network` -> `[x] disable Cache` -> `F5`

Demonstration in Firefox:
(your browser may have the buttons in slightly different places, but it should be similar)

https://github.com/user-attachments/assets/7b0d4859-0ef1-4963-bbf7-8c110c7a7c77

**Comment by Kirin92** [comment]
UGH finally! Thank you! I forgot the cache was a thing...

**Comment by TechnicJelle** [comment]
Yay! I'm glad it works now :partying_face:
